name: jh_legal_affairs
description: A new Flutter project.

version: 0.0.9+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  nav_router:
  intl: 0.16.1
  cached_network_image: 2.0.0
  #网络请求
  dio: 3.0.9
  #数据池
  shared_preferences: 0.5.4
  #轮播图
  flutter_swiper: ^1.1.6
  #二维码
  qr_flutter: ^3.2.0
  toast: 0.1.5
  oktoast: ^2.3.2
  #城市选择器
  city_pickers: ^0.1.30
  #自定义选择器
  flutter_picker: ^1.1.4
  #图片选择器
  image_picker: ^0.6.1
  #富文本
  zefyr: 0.11.0
  quill_delta: ^1.0.0
  #视频播放器
  video_player: 0.10.4+2
  #高德
  amap_location: 0.2.0
  #视频播放配件
  chewie: 0.9.10
  #图表
  charts_flutter: 0.9.0
  #权限
  permission_handler: 4.0.0
  fluwx: 2.1.0
  flutter_alipay: 1.0.0
  share: 0.6.3+6
  flutter_image_compress: 0.6.8
  url_launcher: 5.3.0
  uni_links: 0.4.0
  flutter_video_compress: 0.3.7+8
  photo_view: 0.9.2
  gallery_saver: 2.0.1
  #格式化日期
  date_format: ^1.0.8
  #特殊列表滑动
  azlistview: ^0.1.0
  open_file: 2.1.1
  package_info: 0.4.0+6
  easy_video_compress:
  takingdata_sdk:
    git:
      url: http://git.wzubi.com/Crazyq1/takingdata_sdk.git

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/loading.gif
    - assets/images/mine/
    - assets/images/tab/
    - assets/register/
    - assets/images/business/
    - assets/images/lawyer/
    - assets/images/home/
    - assets/images/commom/
    - assets/images/avatar/
    - assets/images/law_firm/
    - assets/images/
